### ISSUE TITLE
Updates to support Tomcat 10

### ISSUE THREAD

**Issue by micronaut** [spullara/oauth#4]
Hi, I was wondering if there are any plans to update this library support Tomcat 10 (javax.servlet namespace to jakarta.servlet)?  Thanks!

**Comment by spullara** [comment]
This was originally a fork of Google's oauth library (2010!) so I could fix a couple bugs. I'm not even sure if this library is even up to date with the specifications at this point.

**Comment by micronaut** [comment]
Ok, thanks!
